language: python

python:
  - "3.6"

branches:
  only:
    - master

install:
  - wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - cp chromedriver ~/bin/chromedriver
  - pip install selenium

script:
  - bash ./scripts/cron.sh
  - echo "ALL DONE"

after_success:
  - bash ./scripts/deploy.sh
