language: python

sudo: required

python:
  - "3.6.3"

branches:
  only:
    - master

install:
  - wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/chromedriver
  - sudo chmod a+x ~/chromedriver
  - sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
  - sudo chown travis /usr/local/bin/chromedriver
  - pip install selenium

script:
  - set -e
  - whereis google-chrome-stable
  - google-chrome-stable --version
  - whereis chromedriver
  - bash ./scripts/cron.sh
  - echo "ALL DONE"

after_success:
  - bash ./scripts/deploy.sh
