language: python

python:
  - "3.6.3"

branches:
  only:
    - master

install:
  - wget http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.3/
  - export CHROME_BIN=chromium-browser
  - pip install selenium

script:
  - bash ./scripts/cron.sh
  - echo "ALL DONE"

after_success:
  - bash ./scripts/deploy.sh
