language: python

python:
  - "3.6"

branches:
  only:
    - master

install:
  - pip install selenium

script:
  - bash ./scripts/cron.sh
  - echo "ALL DONE"

after_success:
  - bash ./scripts/deploy.sh
